import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

load_dotenv()

app = FastAPI(title="ADK SOC Advisory Agent")

# ---------------------------------------------------------------------------
# ADK Tools: Diagnostic & Advisory Tools
# ---------------------------------------------------------------------------

def check_ip_reputation(ip: str) -> dict:
    """Checks threat intelligence database for a target IP address reputation score and history."""
    is_known_attacker = ip.startswith("192.") or ip.startswith("10.") or int(ip.split(".")[0]) % 2 == 0
    return {
        "ip": ip,
        "reputation_score": 85 if is_known_attacker else 10,
        "historical_flags": 14 if is_known_attacker else 0,
        "status": "MALICIOUS" if is_known_attacker else "BENIGN",
        "threat_category": "Brute Force / Scanner" if is_known_attacker else "Clean"
    }

def get_host_telemetry(hostname: str) -> dict:
    """Fetches real-time host metrics and active log violation counters."""
    is_prod = "prod" in hostname.lower()
    return {
        "hostname": hostname,
        "cpu_load_percent": 92.4 if is_prod else 35.1,
        "recent_violation_count": 47 if is_prod else 2,
        "affected_service": "auth-service" if is_prod else "internal-test"
    }

def calculate_risk_rating(reputation_score: int, violation_count: int) -> dict:
    """Evaluates dynamic risk rating based on threat intelligence and event frequency."""
    composite_score = (reputation_score * 0.6) + (min(violation_count, 50) * 0.8)
    
    if composite_score >= 70:
        rating = "CRITICAL"
    elif composite_score >= 45:
        rating = "HIGH"
    elif composite_score >= 20:
        rating = "MEDIUM"
    else:
        rating = "LOW"

    return {
        "composite_score": round(composite_score, 1),
        "risk_rating": rating
    }

def send_infosec_alert_email(
    to_email: str,
    ip_address: str,
    risk_rating: str,
    violation_count: int,
    potential_fix: str
) -> dict:
    """Dispatches a detailed security advisory email to the InfoSec / SOC team."""
    smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    sender_email = os.getenv("SMTP_SENDER_EMAIL", "soc-alerts@company.com")
    sender_password = os.getenv("SMTP_SENDER_PASSWORD", "")

    subject = f"[{risk_rating} RISK] Security Advisory: Incident Detected from {ip_address}"

    body = f"""
    ======================================================================
    INFOSEC SECURITY ADVISORY & TRIAGE REPORT
    ======================================================================
    Risk Rating         : {risk_rating}
    Source IP Address   : {ip_address}
    Total Violations    : {violation_count}
    Target Endpoint     : Production Infrastructure
    ======================================================================

    RECOMMENDED ACTION / POTENTIAL FIX:
    ----------------------------------------------------------------------
    {potential_fix}

    ----------------------------------------------------------------------
    Note: This is an automated diagnostic advisory generated by the 
    Autonomous SOC Agent. Please review and execute the recommended fix.
    ======================================================================
    """

    # If SMTP credentials are present, send real email; otherwise mock send
    if sender_password:
        try:
            msg = MIMEMultipart()
            msg["From"] = sender_email
            msg["To"] = to_email
            msg["Subject"] = subject
            msg.attach(MIMEText(body, "plain"))

            server = smtplib.SMTP(smtp_server, smtp_port)
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
            server.quit()
            status = "EMAIL_SENT_SUCCESSFULLY"
        except Exception as e:
            status = f"FAILED_TO_SEND_EMAIL: {str(e)}"
    else:
        status = "MOCK_EMAIL_DISPATCHED (Configure SMTP env vars for live email delivery)"

    return {
        "status": status,
        "recipient": to_email,
        "subject": subject
    }

# ---------------------------------------------------------------------------
# Google ADK Agent Setup
# ---------------------------------------------------------------------------

soc_agent = Agent(
    name="soc_advisory_agent",
    model=os.getenv("GEMINI_MODEL", "gemini-2.5-flash"),
    description="Advisory SOC agent for investigating threats and alerting InfoSec.",
    instruction="""
    You are an expert Security Operations (SOC) Advisory Analyst.
    Your objective is to investigate incoming Datadog security alerts, assess risk, and alert InfoSec.

    Step-by-step workflow:
    1. Inspect the source_ip and hostname from the incoming alert log.
    2. Query `check_ip_reputation` for threat score and historical flags.
    3. Query `get_host_telemetry` to retrieve recent violation count.
    4. Pass findings to `calculate_risk_rating` to determine if the risk is LOW, MEDIUM, HIGH, or CRITICAL.
    5. Formulate clear, step-by-step recommended fix instructions (e.g., specific CLI iptables commands, API key resets, or rate-limiting adjustments).
    6. Execute `send_infosec_alert_email` targeting 'infosec-team@company.com' containing the IP, risk rating, violation count, and potential fix.
    7. Synthesize your final report.
    """,
    tools=[
        check_ip_reputation,
        get_host_telemetry,
        calculate_risk_rating,
        send_infosec_alert_email
    ]
)

session_service = InMemorySessionService()
runner = Runner(
    app_name="soc_advisory_app",
    agent=soc_agent,
    session_service=session_service
)

# ---------------------------------------------------------------------------
# FastAPI Endpoint
# ---------------------------------------------------------------------------

class IncidentPayload(BaseModel):
    id: str
    title: str
    text: str
    alert_type: str
    hostname: str
    source_ip: str
    tags: list[str]

@app.post("/analyze")
async def analyze_incident(payload: IncidentPayload):
    try:
        session = await session_service.create_session(
            app_name="soc_advisory_app",
            user_id="n8n_orchestrator",
            state={}
        )
        
        prompt_text = (
            f"NEW DATADOG ALERT RECEIVED:\n"
            f"- Event ID: {payload.id}\n"
            f"- Title: {payload.title}\n"
            f"- Alert Type: {payload.alert_type}\n"
            f"- Hostname: {payload.hostname}\n"
            f"- Source IP: {payload.source_ip}\n"
            f"- Details: {payload.text}\n"
            f"- Tags: {', '.join(payload.tags)}\n\n"
            f"Please conduct the investigation, assess risk rating, formulate recommended fixes, and dispatch the alert email to InfoSec."
        )

        content = types.Content(role="user", parts=[types.Part(text=prompt_text)])
        
        agent_response_text = ""
        tool_calls_executed = []

        events = runner.run(
            app_name="soc_advisory_app",
            user_id="n8n_orchestrator",
            session_id=session.session_id,
            new_message=content
        )

        async for event in events:
            if event.content and event.content.parts:
                for part in event.content.parts:
                    if part.text:
                        agent_response_text += part.text
                    if hasattr(part, "function_call") and part.function_call:
                        tool_calls_executed.append(part.function_call.name)

        return {
            "status": "success",
            "session_id": session.session_id,
            "tool_calls_executed": tool_calls_executed,
            "report": agent_response_text
        }

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"ADK Agent execution failed: {str(e)}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)